### ISSUE TITLE
colorama.init() Incompatible

### ISSUE THREAD

**Issue by Ltuin** [venaxyt/fade#2]
it stops working if you enter colorama.init(), meaning its incompatible with colorama. I'd really like to make some cool UI using fade and colorama pls fix

**Comment by venaxyt** [comment]
Hey bro I really don't know for this, I didn't coded colorama, fade module imports system from os and make an empty commande, it is fade's initiation to be able to fade texts in the console, maybe colorama blocks that or edit ascii mode, I cannot respond you I am sorry, for the moment you only can use one of the two but not both together.
